first commit
Udokaamos/my-site pull request #1
Opened 2019-06-02 18:33 UTC by Udokaamos

Please verify

2019-07-23 20:44 UTC, Udokaamos commented
![image](https://user-images.githubusercontent.com/39133155/61746139-ed534a80-ad92-11e9-971e-0ee56ae3da06.png)

2019-07-23 20:45 UTC, Udokaamos commented
![image](https://user-images.githubusercontent.com/39133155/61746219-1f64ac80-ad93-11e9-9c9c-f4001208dee3.png)

2019-07-23 22:30 UTC, daddychukz commented
Great start!
Take note of the following:
>- Re-arrange your folder structure to have `styles`, `scripts` folders, and rename `img` to `images`.
>- Include relevant files in appropriate directories after creating them (e.g style.css should be in `styles` folder)
>- Ensure proper commit messages. Let your commit message reflect what you actually did in the change you made. Just a summary e.g `Added a new header component`. Do that against `first commit`

2019-07-24 21:14 UTC, daddychukz commented on styles/style.css
> +    background:url('../img/showcase.jpg') no-repeat 0 -400px;
You already changed the folder name so effect the change here...

2019-07-24 21:15 UTC, daddychukz requested changes
Left a comment

2019-07-25 15:53 UTC, daddychukz approved these changes

2019-07-29 01:24 UTC, merged